name: "sr-docker"
services:
  sr-controller:
    image: sr-controller
    build:
      context: ./sr-controller
    environment:
      - SERVER_PORT=10000
    ports:
      - "10000:10000"
    networks:
      - default
      - rocketmq
    volumes:
      - sr-image-data:/app/data/image
      - sr-model-data:/app/data/model

  sr-inference:
    image: sr-inference
    build:
      context: ./sr-inference
    environment:
      - SERVER_PORT=11000
    networks:
      - default
      - rocketmq
    volumes:
      - sr-image-data:/app/data/image
      - sr-model-data:/app/data/model

  sr-redis:
    image: redis
    container_name: sr-redis
    ports:
      - "6379:6379"
    volumes:
      - sr-redis-data:/data

  sr-nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: sr-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - sr-nacos-data:/home/nacos

  sr-sentinel:
    container_name: sr-sentinel
    build:
      context: ./sentinel
    ports:
      - "8088:8080"

  sr-rocketmq-nameserver:
    image: apache/rocketmq:5.3.2
    container_name: sr-rocketmq-nameserver
    ports:
      - "9876:9876"
    networks:
      - rocketmq
    command: sh mqnamesrv
    volumes:
      - sr-rocketmq-data:/home/rocketmq

  sr-rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: sr-rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=sr-rocketmq-nameserver:9876
    depends_on:
      - sr-rocketmq-nameserver
    networks:
      - rocketmq
    command: sh mqbroker -c ../conf/broker.conf
    volumes:
      - sr-rocketmq-data:/home/rocketmq

  sr-rocketmq-proxy:
    image: apache/rocketmq:5.3.2
    container_name: sr-rocketmq-proxy
    networks:
      - rocketmq
    depends_on:
      - sr-rocketmq-nameserver
      - sr-rocketmq-broker
    ports:
      - "8089:8080"
      - "8081:8081"
    restart: on-failure
    environment:
      - NAMESRV_ADDR=sr-rocketmq-nameserver:9876
    command: sh mqproxy
    volumes:
      - sr-rocketmq-data:/home/rocketmq

networks:
  rocketmq:
    driver: bridge

volumes:
  sr-image-data:
  sr-model-data:
  sr-redis-data:
  sr-nacos-data:
  sr-rocketmq-data: